name: helloworld script

on:
  push:
    paths:
      - "**/*.py"

jobs:
  sayHelloScript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up python
      uses: actions@setup-python@5        

    - name: print helloworld
      run: python hello.py

