name: helloworld script

on:
  push:
    paths:
      - "**/*.py"

jobs:
  sayHelloScript:
    runs-on: ubuntu-latest

    steps:
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: 5.1.0

    - name: print helloworld
      run: python hello.py

